In [1]:
import sys
import numpy as np

## ARRAYS
NumPy nos permite hacer operaciones en cadenas (sumas, restas, operaciones estadisticas, etc)

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b.dtype

dtype('float64')

In [16]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [17]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [18]:
c = np.array(['a', 'b', 'c'])

In [19]:
c.dtype

dtype('<U1')

In [20]:
d = np.array([{'a': 1}, sys])

In [21]:
d.dtype

dtype('O')

## Dimensiones y formas

In [22]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [23]:
A.shape

(2, 3)

In [24]:
A.ndim

2

In [25]:
A.size #numero de elementos

6

In [26]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [27]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [28]:
B.shape

(2, 2, 3)

In [29]:
B.ndim

3

In [30]:
B.size

12

## Indexando matrices

In [31]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [32]:
A[1]

array([4, 5, 6])

In [33]:
A[1][0]

4

In [34]:
A[1, 0]

4

In [35]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
A[:, :2] #selecciona todas las filas y solo las 2 primeras columnas

array([[1, 2],
       [4, 5],
       [7, 8]])

In [37]:
A[:2, :2] #primeras 2 filas y primeras 2 columnas

array([[1, 2],
       [4, 5]])

In [38]:
A[:2, 2:] #primeras 2 filas y la columna 2 en adelante

array([[3],
       [6]])

In [39]:
A[1] = np.array([10, 10, 10]) #se asigna los valores a la fila 1

In [40]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [41]:
A[2] = 99 #se asigna los valores a la fila 2

In [42]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Operaciones Estadisticas

In [43]:
a = np.array([1, 2, 3, 4])

In [44]:
a

array([1, 2, 3, 4])

In [45]:
a.sum()

10

In [46]:
a.mean()

2.5

In [47]:
a.std() #desviacion estandar 

1.118033988749895

In [48]:
a.var() #Variacion

1.25

In [49]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [50]:
A.sum()

45

In [51]:
A.mean()

5.0

In [52]:
A.std()

2.581988897471611

In [53]:
A.sum(axis=0) #suma por columnas 

array([12, 15, 18])

In [54]:
A.sum(axis=1) #Suma por filas

array([ 6, 15, 24])

In [55]:
A.mean(axis=0) #media por columnas

array([4., 5., 6.])

In [56]:
A.mean(axis=1) #media por filas

array([2., 5., 8.])

In [57]:
A.std(axis=0) #desviacion estandar por columnas

array([2.44948974, 2.44948974, 2.44948974])

In [58]:
A.std(axis=1) #Desviacion estandar por columnas

array([0.81649658, 0.81649658, 0.81649658])

## Vectorizacion de operaciones

In [59]:
a = np.arange(4)

In [60]:
a


array([0, 1, 2, 3])

In [61]:
a + 10 #suma a cada elemento del array 10

array([10, 11, 12, 13])

In [62]:
a * 10 #multiplica a cada elemento del array por 10

array([ 0, 10, 20, 30])

In [63]:
a += 100 #adiciona 100 a cada elemento del array y lo guarda en a

In [64]:
a

array([100, 101, 102, 103])

In [65]:
l = [0, 1, 2, 3]

In [66]:
[i * 10 for i in l] 

[0, 10, 20, 30]

In [67]:
b = np.array([10, 10, 10, 10])

In [68]:
a + b

array([110, 111, 112, 113])

In [69]:
a * b #para operar arrays se necesita que tengan la misma cantidad de elementos

array([1000, 1010, 1020, 1030])

## Boleanos con arrays

In [70]:
a = np.arange(4)

In [71]:
a

array([0, 1, 2, 3])

In [72]:
a[0], a[-1]

(0, 3)

In [73]:
a[[0, -1]]

array([0, 3])

In [74]:
a[[True, False, False, True]]

array([0, 3])

In [75]:
a >= 2

array([False, False,  True,  True])

In [76]:
a[a >= 2] #si se cumple la condicion devuelve True

array([2, 3])

In [77]:
a.mean()

1.5

In [78]:
a[a > a.mean()]

array([2, 3])

In [79]:
a[~(a > a.mean())] #devuelve los objetos que no son mayores a la media

array([0, 1])

In [80]:
a[(a == 0) | (a == 1)] #or

array([0, 1])

In [81]:
a[(a <= 2) & (a % 2 == 0)] #and

array([0, 2])

In [82]:
A = np.random.randint(100, size=(3, 3))

In [83]:
A

array([[45, 21, 25],
       [43, 52, 17],
       [36, 66, 55]])

In [84]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([45, 25, 52, 36, 55])

In [85]:
A > 30

array([[ True, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [86]:
A[A > 30]

array([45, 43, 52, 36, 66, 55])

## Algebra lineal

In [87]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [88]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [89]:
A.dot(B) #producto punto

array([[20, 14],
       [56, 41],
       [92, 68]])

In [90]:
A @ B #producto cruz

array([[20, 14],
       [56, 41],
       [92, 68]])

In [91]:
B.T #Transpuesta

array([[6, 4, 2],
       [5, 3, 1]])

In [92]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Tamaño de objetos en la memoria

INTEGERS Y FLOATS

In [93]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [94]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [95]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [96]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [97]:
np.dtype(float).itemsize

8

LISTAS

In [98]:
# A one-element list
sys.getsizeof([1])

64

In [99]:
# An array of one element in numpy
np.array([1]).nbytes

4

RENDIMIENTO

In [100]:
l = list(range(100000)) #Lista de los primeros 100000 numeros

In [101]:
a = np.arange(100000) #array de los primeros 100000 numeros

In [102]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


216474736

In [103]:
%time sum([x ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 12 ms


333328333350000

## FUNCIONES NUMPY

RANDOM

In [104]:
np.random.random(size=2)

array([0.97639812, 0.32772441])

In [105]:
np.random.normal(size=2)

array([0.58312017, 0.27411937])

In [106]:
np.random.rand(2, 4)

array([[0.59776055, 0.66051228, 0.52250297, 0.84090812],
       [0.50658366, 0.92364171, 0.33507547, 0.83165307]])

ARRANGE

In [107]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [109]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

RESHAPE

In [110]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [111]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

LINSCAPE

In [112]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [113]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [114]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

ZEROS, ONES, EMPTYS

In [115]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [116]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [117]:
np.zeros((3, 3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [118]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [119]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [120]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [121]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

IDENTIDAD Y OJO

In [122]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [125]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [126]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [127]:
"Hello World"[6]

'W'

## Ejercicios

In [128]:
np.arange(10,50) #array con numeros del 10 al 49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [131]:
np.ones([2,2], dtype=np.int8) #Matriz 2x2 llena de unos

array([[1, 1],
       [1, 1]], dtype=int8)

In [133]:
np.ones([3,2], dtype=np.float64) #Matriz 3x2 llena de unos

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [135]:
X = np.arange(4, dtype=np.int8)
#variable X con 4 elementos
np.ones_like(X) #array con la misma forma de X llena de unos

array([1, 1, 1, 1], dtype=int8)

In [137]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int8)
#variable X con 6 elementos
np.zeros_like(X) #array con la misma forma de X llena de ceros

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [139]:
np.ones([4,4], dtype=np.int8) * 5
#Matriz 4x4 llena de 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

In [140]:
np.identity(3) #Matriz identidad de 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
np.random.randint(10, size=3)
#Matrizcon 3 numeros random entre el 1 al 10

array([9, 2, 1])

In [143]:
np.random.randn(3,3,3) 
#Matriz 3x3x3 llena con numeros random entre el 0 al 1

array([[[ 0.1606931 ,  0.0504576 , -1.17605681],
        [ 0.35843355,  1.17088329,  0.58705585],
        [ 0.72875138,  0.0133039 ,  0.23686986]],

       [[ 0.98793375, -0.87789464,  1.25453312],
        [ 1.03933289,  0.78047623,  0.01614343],
        [-0.8161924 ,  1.52832599,  0.07548044]],

       [[-0.16006558, -0.22767768,  1.23780793],
        [ 0.10429064,  0.44335711, -0.79808621],
        [-1.56254949,  2.13376236,  0.04461433]]])

In [144]:
#Convertir la lista python en array NumPy
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [146]:
#Crear una copia del array X
X = np.array([5,2,3], dtype=np.int8)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 1693281410704
[5 2 3] 1693281882480


In [149]:
np.arange(1, 11, 2) #con numeros impares entre el 1 al 10

array([1, 3, 5, 7, 9])

In [150]:
np.arange(1, 11)[::-1] #numeros del 1 al 10 en orden descendente

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [151]:
#Organiza los elementos
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

In [152]:
#cambia la ultima fila con unos
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [154]:
#Camnia el ultimo item por 0
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [155]:
#solo muestra los elementos negativos
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [157]:
#solo muestra los elementos negativos
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [158]:
#Solo muestra los elementos mayores a la media
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

In [159]:
#Devuelve True si ningun elemento es cero
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

In [160]:
#Devuelve True si algun elemento es cero
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True